### ISSUE TITLE
Backend framework selection

### ISSUE THREAD

**Issue by Cyberunner23** [SOEN341-UA/SOEN341#1]
Which framework would you like to use for our backend?
=============================================

[![](https://api.gh-polls.com/poll/01C4A9B5D4C5CZ00WS95KRK5VV/php)](https://api.gh-polls.com/poll/01C4A9B5D4C5CZ00WS95KRK5VV/php/vote)
[![](https://api.gh-polls.com/poll/01C4A9B5D4C5CZ00WS95KRK5VV/Ruby%20on%20Rails)](https://api.gh-polls.com/poll/01C4A9B5D4C5CZ00WS95KRK5VV/Ruby%20on%20Rails/vote)
[![](https://api.gh-polls.com/poll/01C4A9B5D4C5CZ00WS95KRK5VV/Node.js)](https://api.gh-polls.com/poll/01C4A9B5D4C5CZ00WS95KRK5VV/Node.js/vote)
[![](https://api.gh-polls.com/poll/01C4A9B5D4C5CZ00WS95KRK5VV/Python)](https://api.gh-polls.com/poll/01C4A9B5D4C5CZ00WS95KRK5VV/Python/vote)

**Comment by Lussier115** [comment]
Personally I do not know much of them but php would be more useful for me for jobs and stuff. Id prefer learning and using php to get better at it.

**Comment by Lussier115** [comment]
php or node.js  👍

**Comment by Cyberunner23** [comment]
then vote for it by clicking on php

**Comment by Lussier115** [comment]
I know, just stating my reason why im voting for that

**Comment by Cyberunner23** [comment]
ok

**Comment by Cyberunner23** [comment]
Ok so Node.js it is!
